pool: Azure Pipelines

steps:
  - checkout: self

  - task: UseNode@1
    inputs:
      versionSpec: '16.x'  # Ensure the correct Node.js version, adjust as per project requirements

  - script: |
      npm install --legacy-peer-deps --verbose
    displayName: 'npm install with legacy peer deps'



  - task: SnykSecurityScan@1
    inputs:
      serviceConnectionEndpoint: 'SNYK_TOKEN'
      testType: 'app'
      severityThreshold: 'critical'
      monitorWhen: 'always'
      failOnIssues: true
      additionalArguments: '--fail-on=all'

  - task: SnykSecurityScan@1
    inputs:
      serviceConnectionEndpoint: 'SNYK_TOKEN'
      testType: 'code'
      failOnIssues: true
